#注：yml无法被@PropertySource加载
server:
  port: 8082
  servlet:
    context-path: /cc-service

app:
  name: cf-service
spring:
  profiles:
    active: dev
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver

#logging:
#  level:
#    com.vcredit: info
#  file: "E:/test.log"
#  max-size: 1
#  pattern:
#    dateformat: yyyy-MM-dd

#mapper.xml配置
mybatis:
  mapper-locations: classpath:com/vcredit/persistence/xml/*Mapper.xml
  configuration-properties:
    dialect: mysql


---

spring:
  profiles: dev
  devtools:
    restart:
      enabled: true
  http:
      encoding:
        charset: UTF-8
        enabled: true
        force: true
server:
  tomcat:
    uri-encoding: UTF-8
#  datasource:
#    password: miaofen_dev
#    username: dev
#    url: jdbc:mysql://10.138.60.74:3306/miaofen_shop?useUnicode=true&characterEncoding=utf-8&serverTimezone=Shanghai
datasource:
  url: jdbc:mysql://:3306/coop_common?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
  username: 
  password: 

log:
  level: info
  pattern:
    console: "%green(%date) %highlight(%level) [%yellow(%thread)]  %magenta(%class) %cyan([%file:%line]) - %msg%n %ex"

---

spring:
  profiles: test

datasource:
  url: jdbc:mysql://:3306/coop_common?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
  username: 
  password: 
log:
  level: info
  pattern:
    console: "%date %level [%thread]  [%class:%line] - %msg%n %ex{short}"

---

spring:
  profiles: prd

datasource:
  url:
  username:
  password:
log:
  level: info
  pattern:
    console: "%date %level [%thread]  [%class:%line] - %msg%n %ex{short}"
