#注：yml无法被@PropertySource加载
server:
  port: 8081

app:
  name: cf-service
spring:
  profiles:
    active: dev



#mapper.xml配置
mybatis:
  mapper-locations: classpath:com/vcredit/persistence/xml/*Mapper.xml
  configuration-properties:
    dialect: mysql


---

spring:
  profiles: dev
  devtools:
    restart:
      enabled: true
  thymeleaf:
    cache: false

#    url: jdbc:mysql://:3306/miaofen_shop?useUnicode=true&characterEncoding=utf-8&serverTimezone=Shanghai
datasource:
  url: jdbc:mysql://:3306/coop_common?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
  username:
  password: A!

log:
  level: info
  pattern:
    console: "%green(%date) %highlight(%level) [%yellow(%thread)]  %magenta(%class) %cyan([%file:%line]) - %msg%n %ex"

---

spring:
  profiles: test

server:
  port: 8082
datasource:
  url: jdbc:mysql://:3306/coop_common?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
  username:
  password: A!
log:
  level: info
  pattern:
    console: "%date %level [%thread]  [%class:%line] - %msg%n %ex{short}"

---

spring:
  profiles: prd

server:
  port: 8083
datasource:
  url:
  username:
  password:
log:
  level: info
  pattern:
    console: "%date %level [%thread]  [%class:%line] - %msg%n %ex{short}"
